# PHP
#export WEB_PATH=/home/wangxh/ddapi
#$ docker-compose up          # WEB_PATH will be /Users/php/ddapi

version: '2'

services:

  phpfpm:
    build: ./.docker/images/php-fpm
    volumes:
      - ./.docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./.docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${WEB_PATH}:/var/www/html
      - ./.docker/images/php-fpm/entrypoint.sh /usr/local/bin/entrypoint.sh
    external_links:
      - rabbitmq:rabbitmq.docker
      - redis:redis.docker
      - tsdbrelay:tsdbrelay.docker
      - bosun:bosun.docker
    networks:
      - dockerbosun_default
    command: entrypoint.sh

  nginx-app:
    image: nginx
    #environment:
    #  - TIMEZONE:Asia/Shanghai
    ports:
      - "8081:80"
    volumes:
      - ./.docker/images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ${WEB_PATH}:/var/www/html
    external_links:
      - rabbitmq:rabbitmq.docker
      - redis:redis.docker
      - tsdbrelay:tsdbrelay.docker
      - bosun:bosun.docker
    networks:
      - dockerbosun_default

  php-worker-host:
    build: ./.docker/images/php-work
    volumes:
      - ${WEB_PATH}:/usr/share/nginx/html/ddapi
      - ./.docker/images/php-work/host.sh /usr/local/bin/entrypoint.sh
    command: entrypoint.sh
    external_links:
      - rabbitmq:rabbitmq.docker
      - redis:redis.docker
      - tsdbrelay:tsdbrelay.docker
      - bosun:bosun.docker
    networks:
      - dockerbosun_default

  php-worker-venter:
    build: ./.docker/images/php-work
    volumes:
      - ${WEB_PATH}:/usr/share/nginx/html/ddapi
      - ./.docker/images/php-work/vcenter.sh /usr/local/bin/entrypoint.sh
    command: entrypoint.sh
    external_links:
      - rabbitmq:rabbitmq.docker
      - redis:redis.docker
      - tsdbrelay:tsdbrelay.docker
      - bosun:bosun.docker
    networks:
      - dockerbosun_default

  php-worker-metric:
    build: ./.docker/images/php-work
    volumes:
      - ${WEB_PATH}:/usr/share/nginx/html/ddapi
      - ./.docker/images/php-work/metric.sh /usr/local/bin/entrypoint.sh
    command: entrypoint.sh
    external_links:
      - rabbitmq:rabbitmq.docker
      - redis:redis.docker
      - tsdbrelay:tsdbrelay.docker
      - bosun:bosun.docker
    networks:
      - dockerbosun_default

networks:
  dockerbosun_default:
    external: true